import React from "react";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

import { Header } from "@/components/layout/header";

import "./globals.css";

const notoSans = Noto_Sans({
   subsets: ["latin"],
   display: "swap",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={notoSans.className}>
         <body className="antialiased">
            <Header />
            {children}
         </body>
      </html>
   );
}
